# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/skysk/Documents/Vivado_Projects/vga_port/vga_port.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_3/BRAM_blk_mem_gen_0_3.xci
# IP: The module: 'BRAM_blk_mem_gen_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/skysk/Documents/Vivado_Projects/vga_port/vga_port.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_3/BRAM_blk_mem_gen_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_blk_mem_gen_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/skysk/Documents/Vivado_Projects/vga_port/vga_port.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_3/BRAM_blk_mem_gen_0_3.xci
# IP: The module: 'BRAM_blk_mem_gen_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/skysk/Documents/Vivado_Projects/vga_port/vga_port.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_3/BRAM_blk_mem_gen_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_blk_mem_gen_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
