# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Basys3_Master.xdc

# Block Designs: bd/BRAM/BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM || ORIG_REF_NAME==BRAM} -quiet] -quiet

# IP: bd/BRAM/ip/BRAM_blk_mem_gen_0_3/BRAM_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_blk_mem_gen_0_3 || ORIG_REF_NAME==BRAM_blk_mem_gen_0_3} -quiet] -quiet

# XDC: bd/BRAM/BRAM_ooc.xdc
